"""Criação das tabelas vendedor, cliente, vendas, comissao

Revision ID: 0bc6a259d9ff
Revises: 
Create Date: 2024-09-10 17:33:03.297648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bc6a259d9ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afiliados')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendedor_clientes', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vendedores', ['vendedor_id'], ['id'], referent_schema='limpa_nome')

    with op.batch_alter_table('comissao', schema=None) as batch_op:
        batch_op.drop_constraint('fk_afiliado_comissao', type_='foreignkey')
        batch_op.drop_constraint('fk_vendedor_comissao', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vendedores', ['afiliado_id'], ['id'], referent_schema='limpa_nome')
        batch_op.create_foreign_key(None, 'vendedores', ['vendedor_id'], ['id'], referent_schema='limpa_nome')

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendedor_vendas', type_='foreignkey')
        batch_op.drop_constraint('fk_cliente_vendas', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'], referent_schema='limpa_nome')
        batch_op.create_foreign_key(None, 'vendedores', ['vendedor_id'], ['id'], referent_schema='limpa_nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_cliente_vendas', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_vendedor_vendas', 'vendedor', ['vendedor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comissao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_vendedor_comissao', 'vendedor', ['vendedor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_afiliado_comissao', 'vendedor', ['afiliado_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_vendedor_clientes', 'vendedor', ['vendedor_id'], ['id'], ondelete='CASCADE')

    op.create_table('afiliados',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('vendedor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_afiliacao', sa.DATE(), server_default=sa.text('curdate()'), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'Ativo'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['site.user.id'], name='fk_user_afiliado', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], name='fk_vendedor_afiliados', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vendedor',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('indicacoes', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('vendas_fechadas', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('vendas_concluidas', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('afiliados', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('afiliados_ids', mysql.TEXT(), nullable=True),
    sa.Column('comissao_acumulada', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('data_ultima_venda', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'Ativo'"), nullable=True),
    sa.Column('data_criacao', sa.DATE(), server_default=sa.text('curdate()'), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tipo_vendedor', mysql.VARCHAR(length=50), server_default=sa.text("'Afiliado'"), nullable=True),
    sa.Column('nivel', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('id_encadeado', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['site.user.id'], name='fk_user_site', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('vendedores', schema='limpa_nome')
    # ### end Alembic commands ###
